#!/usr/bin/env node
/**
 * compile-tokens.js
 *
 * Reads 00_DESIGN_SYSTEM/tokens.yaml, validates against tokens.schema.json,
 * generates per-format outputs in 00_DESIGN_SYSTEM/compiled/:
 *
 *   tokens.tex   - LaTeX preamble (consumed by render-pdf, render-latex)
 *   tokens.css   - CSS custom properties (consumed by HTML preview)
 *   tokens.json  - Structured form (consumed by render scripts)
 *
 * No external processes are spawned by this script. It only reads YAML/JSON
 * and writes generated text files.
 */

const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');
const Ajv = require('ajv');
const addFormats = require('ajv-formats');

const REPO_ROOT = path.resolve(__dirname, '..');
const TOKENS_PATH = path.join(REPO_ROOT, '00_DESIGN_SYSTEM', 'tokens.yaml');
const SCHEMA_PATH = path.join(REPO_ROOT, '00_DESIGN_SYSTEM', 'schemas', 'tokens.schema.json');
const OUT_DIR = path.join(REPO_ROOT, '00_DESIGN_SYSTEM', 'compiled');

function fail(msg) {
  console.error(`compile-tokens: ${msg}`);
  process.exit(1);
}

function hexToRgb(hex) {
  const m = /^#([0-9a-f]{6})$/i.exec(hex);
  if (!m) return '0,0,0';
  const n = parseInt(m[1], 16);
  return `${(n >> 16) & 255},${(n >> 8) & 255},${n & 255}`;
}

function buildLatexPreamble(tokens) {
  const lines = [];
  lines.push('% Generated by scripts/compile-tokens.js - do not edit by hand.');
  lines.push(`% Source: 00_DESIGN_SYSTEM/tokens.yaml (version ${tokens.version})`);
  lines.push('');
  lines.push('% Fonts (requires LuaLaTeX with fontspec)');
  lines.push('\\usepackage{fontspec}');
  lines.push(`\\setmainfont{${tokens.typography.body_font}}`);
  lines.push(`\\setsansfont{${tokens.typography.heading_font}}`);
  lines.push(`\\setmonofont{${tokens.typography.code_font}}`);
  lines.push('');
  lines.push('% Type metrics');
  lines.push(`\\renewcommand{\\baselinestretch}{${tokens.typography.line_height}}`);
  lines.push('');
  lines.push('% Colors');
  lines.push('\\usepackage[table,RGB]{xcolor}');
  lines.push(`\\definecolor{textcolor}{RGB}{${hexToRgb(tokens.colors.text)}}`);
  lines.push(`\\definecolor{accentcolor}{RGB}{${hexToRgb(tokens.colors.accent)}}`);
  lines.push(`\\definecolor{linkcolor}{RGB}{${hexToRgb(tokens.colors.link)}}`);
  if (tokens.colors.code_background) {
    lines.push(`\\definecolor{codebgcolor}{RGB}{${hexToRgb(tokens.colors.code_background)}}`);
  }
  lines.push('');
  lines.push('% Page geometry');
  lines.push('\\usepackage{geometry}');
  const margin = (tokens.spacing && tokens.spacing.page_margin) || '1in';
  lines.push(`\\geometry{margin=${margin}}`);
  lines.push('');
  lines.push('% Hyperlink styling');
  lines.push('\\usepackage{hyperref}');
  lines.push('\\hypersetup{colorlinks=true,linkcolor=linkcolor,urlcolor=linkcolor,citecolor=accentcolor}');
  return lines.join('\n') + '\n';
}

function buildCss(tokens) {
  const lines = [];
  lines.push('/* Generated by scripts/compile-tokens.js - do not edit by hand. */');
  lines.push(`/* Source: 00_DESIGN_SYSTEM/tokens.yaml (version ${tokens.version}) */`);
  lines.push(':root {');
  lines.push(`  --font-body: "${tokens.typography.body_font}", serif;`);
  lines.push(`  --font-heading: "${tokens.typography.heading_font}", sans-serif;`);
  lines.push(`  --font-code: "${tokens.typography.code_font}", monospace;`);
  lines.push(`  --font-size-base: ${tokens.typography.base_size};`);
  lines.push(`  --line-height-base: ${tokens.typography.line_height};`);
  lines.push(`  --color-text: ${tokens.colors.text};`);
  lines.push(`  --color-background: ${tokens.colors.background};`);
  lines.push(`  --color-accent: ${tokens.colors.accent};`);
  lines.push(`  --color-link: ${tokens.colors.link};`);
  if (tokens.colors.code_background) {
    lines.push(`  --color-code-bg: ${tokens.colors.code_background};`);
  }
  lines.push('}');
  return lines.join('\n') + '\n';
}

function main() {
  if (!fs.existsSync(TOKENS_PATH)) fail(`tokens.yaml not found at ${TOKENS_PATH}`);
  if (!fs.existsSync(SCHEMA_PATH)) fail(`tokens.schema.json not found at ${SCHEMA_PATH}`);

  let tokens;
  try {
    tokens = yaml.load(fs.readFileSync(TOKENS_PATH, 'utf8'));
  } catch (e) {
    fail(`tokens.yaml parse error: ${e.message}`);
  }

  const ajv = new Ajv({ allErrors: true, strict: false });
  addFormats(ajv);
  const schema = JSON.parse(fs.readFileSync(SCHEMA_PATH, 'utf8'));
  const validate = ajv.compile(schema);
  if (!validate(tokens)) {
    console.error('tokens.yaml failed schema validation:');
    for (const err of validate.errors) {
      console.error(`  ${err.instancePath || '/'}: ${err.message}`);
    }
    process.exit(1);
  }

  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(path.join(OUT_DIR, 'tokens.tex'), buildLatexPreamble(tokens));
  fs.writeFileSync(path.join(OUT_DIR, 'tokens.css'), buildCss(tokens));
  fs.writeFileSync(path.join(OUT_DIR, 'tokens.json'), JSON.stringify(tokens, null, 2));

  console.log(`compile-tokens: wrote ${OUT_DIR}/{tokens.tex, tokens.css, tokens.json}`);
  console.log(`  version: ${tokens.version}`);
}

main();
